export const defaultTerms = [
    'Current Events',
    'Wallpapers',
    // '3D Renders',
    'Textures',
    'Patterns',
    'Experimental',
    'Architecture',
    'Nature',
    'Business & Work',
    'Fashion',
    // 'Film',
    'Food & Drink',
    'Health & Wellness',
    'Animals',
    'Fitness',
    'People',
    // 'Interiors',
    // 'Street Photography',
    'Travel',
    // 'Spirtuality',
    // 'Arts & Culture',
    // 'History',
    'Athletics',
]
