export const defaultTerms = [
    'Current Events',
    'Wallpapers',
    // '3D Renders',
    'Textures',
    'Patterns',
    'Experimental',
    'Architecture',
    'Nature',
    'Business & Work',
    'Fashion',
    // 'Film',
    'Food & Drink',
    'Health & Wellness',
    'Animals',
    'Fitness',
    'People',
    // 'Interiors',
    // 'Street Photography',
    'Travel',
    // 'Spirtuality',
    // 'Arts & Culture',
    // 'History',
    'Athletics',
]

export const artistTerms = [
    'Alfred Sisley',
    'Atey Ghailan',
    'Brandon Woelfel',
    'Chris Moore',
    'David Chipperfield',
    'Edward Ruscha',
    'Enki Bilal',
    'Erin Hanson',
    'George Birrell',
    'Graham Sutherland',
    'Harold Edgerton',
    'Henry Moret',
    'Hiroshi Nagai',
    'Joel Meyerowitz',
    'John Dyer Baizley',
    'Jean Giraud',
    'Mary Blair',
    'Michael Kaluta',
    'Robert McCall',
    'Wong Kar-wai',
]
