name: Run Cypress on push
on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

jobs:
  generate_file_list:
    runs-on: ubuntu-latest
    outputs:
      spec: ${{ steps.list_files.outputs.spec }}
    steps:
      - name: List Files
        id: list_files
        run: |
          # List all the .cy.js files in the cypress/e2e directory
          # and output their file names without the extension
          echo "spec=$(ls cypress/e2e/*.cy.js | xargs -I{} basename {} .cy.js | jq -R -s 'split("\n") | map(select(length > 0))')" >> "$GITHUB_OUTPUT"
  build:
    name: Build node modules
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        id: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install npm dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci

  test:
    name: WordPress (${{ matrix.spec }})
    concurrency:
      group: cypress - ${{ github.event.pull_request.number || github.ref }} - ${{ matrix.spec }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    needs: [build, generate_file_list]
    strategy:
      fail-fast: false
      matrix:
        spec: ${{ fromJson(needs.generate_file_list.outputs.spec) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Restore node modules cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-modules-
      - name: Build
        run: |
          npx eslint --max-warnings 0 .
          npm run build
      - name: Start server
        run: |
          npx wp-env start
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          spec: cypress/e2e/${{ matrix.spec }}.cy.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
